### ISSUE TITLE
calendar bug

### ISSUE THREAD

**Issue by juliefab** [robandjulie/cwbugs#8] opened 2015-02-08 18:29 UTC
![Issue screenshot](https://trackducks.s3.amazonaws.com/crop/54d24f1ecfb07a2d4c0b96c7-1423420140051-62-102)
- Browser: Firefox 37
- OS: Mac OS
- Screen: 1901 x 942

[More details](https://app.trackduck.com/#/project/54d24f1ecfb07a2d4c0b96c7/issue/54d7aabe706a110e6f764cab)

**Comment by bitsandbooks** [comment] 2015-02-08 20:05
Duplicate of issue #1. closing.

**Closed as completed by bitsandbooks** 2015-02-08 20:05 UTC
Labels: duplicate, wontfix, TrackDuck
